### ISSUE TITLE
Receiving Install Error when attempting to load system.json

### ISSUE THREAD

**Issue by Nehtanoj** [Pjb518/FoundryVTT-Level-Up-Official#1]
Receiving the following error message when attempting to install the system.json from the link: 

https://github.com/Pjb518/FoundryVTT-Level-Up-Official/releases/download/0.1.0/system.json

Installation failed: the "path" argument must be of type string. Received undefined.
![Screenshot 2022-01-13 124212](https://user-images.githubusercontent.com/4443634/149381553-99901560-a4be-4211-824f-cf383d022f2e.png)

Using Foundry Version: Version 9 - Build 242 - Stable

**Comment by Shadoghast** [comment]
Yep, same

**Comment by Pjb518** [comment]
@Nehtanoj @Shadoghast If you look at the heading of that dialog window, you're attempting to install a world. You need to be on the systems tab where you can install a system 🙂

**Comment by Pjb518** [comment]
![image](https://user-images.githubusercontent.com/33249712/149383356-b6db9229-9115-430f-bf55-22f8070228e3.png)

**Comment by Nehtanoj** [comment]
> ![image](https://user-images.githubusercontent.com/33249712/149383356-b6db9229-9115-430f-bf55-22f8070228e3.png)

And I'm clearly an idiot lol

Thanks Pjb

Issue resolved was installed under systems
