### ISSUE TITLE
BUG: issue with data storage and display for Saving Throw Configuration of Item

### ISSUE THREAD

**Issue by PhyDoesStuff** [Pjb518/FoundryVTT-Level-Up-Official#10]
Currently, the data value for the Saving Throw Type is being saved in the Rarity field of the Item:

![image](https://user-images.githubusercontent.com/17521733/155870231-aadd38e4-e78c-4194-88cf-f089c7d88079.png)
![image](https://user-images.githubusercontent.com/17521733/155870238-3c87ece6-2379-4172-a644-3b53a4b46c02.png)

Additionally, "Effect of Successful Save" is not displaying in the collapsed view even when the field is populated:
![image](https://user-images.githubusercontent.com/17521733/155870245-2f1f9c7c-b1e0-4ffc-abad-c176feba9846.png)
![image](https://user-images.githubusercontent.com/17521733/155870269-c17cfdf7-cf7b-41c7-a854-fdaae5c10c14.png)

Steps to reproduce Saving Throw Type issue:
1. create new Item
2. Expand Saving Throw Configuration
3. Select one of the Saving Throw Types
4. Check Object Property -> Rarity in collapsed view
This applies in cases where Rarity has been set and where it was never set before.

Steps to reproduce Effect of Successful Save display error:
1. create new Item
2. Expand Saving Throw Configuration
3. Populate "Effect of Successful Save" text box
4. Collapse Saving Throw Configuration, review "Effect of Successful Save" section

**Comment by Pjb518** [comment]
Hey,

Thanks for the report.

These issues are actually directly connected and down to a bad update key on the saving throw ability selection. Setting this would set the rarity property of the Item by mistake, and this has a knock on effect for other parts of the saving throw interface. Importantly certain conditional checks wouldn't work as expected in the display logic for the saving throw summary.

I've pushed a change to the development branch that will make it into 0.5.3 later today. I'll close the issue when that is out.

**Comment by Pjb518** [comment]
0.5.3 has been released and includes a fix for this issue 🙂
