### ISSUE TITLE
[Feat] Migration for `@mod`

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#103]
We need to add a migration script to change all instances of `@mod` to `@abl.mod`

**Comment by Jor-awesome** [comment]
I can try to give this a go, not that much experience unfortunately. Is there an example of implementation anywhere that I can work off?

**Comment by Jor-awesome** [comment]
`function filterByValue(array, value) {
   return array.filter((data) =>  JSON.stringify(data).toLowerCase().indexOf(value.toLowerCase()) !== -1);
};

function migrateActorData(actor) {
	console.log(actor);
	let updateData = {};
	const actorItems = actor.items;

	//console.log(actorItems);

	if (actorItems !== undefined || actorItems !== null) {

		// find if there are actorItems that have a damage formula that needs to change.
		let changeItems = filterByValue(actorItems, '@mod');
		
		console.log(changeItems);


		// skip if no items on the actor have a @mod value
		if (changeItems.length >0) {
		
			for (let b = 0; b < changeItems.length; b++) {
				let formulaArray = changeItems[b].system.damage;				
			
				for (let c = 0; c < formulaArray.length; c++) {
					let formulaStr = formulaArray[c].formula;

					// replace the Old string with the new String
					let oldString = '@mod';
					let newString = '@abl.mod';
					let finalStr = formulaStr.replace(oldString,newString);
					formulaArray[c].formula = finalStr;
				};
						 
                                changeItems[b].update({"system.damage": formulaArray});
			};

		};
	};
 };

let actorWorldArray = game.actors;
const actorArray = Array.from(actorWorldArray);

for (let a = 0; a < actorArray.length; a++) {
	migrateActorData(actorArray[a]);
};`

**Comment by Jor-awesome** [comment]
Like the above or something in a world script ie...?

` hooks.once("ready",function () {
	if (!game.user.isGM( {
		return;
	}
	
	const currentVersion = game.setting.get("a5e:, "systemMigrationVersion");
	const NEEDS_MIGRATION_VERSION = 0,01;
	
	const needMigration = !currentVersion || isNewerVersion(NEEDS_MIGRATION_VERSION, currentVersion);
	
	if (needsMigrations) {
		migrateWorld();
	}
 
 });`
