### ISSUE TITLE
[Bug] Instalation error

### ISSUE THREAD

**Issue by Melon-PieldeSapo** [Pjb518/FoundryVTT-Level-Up-Official#107]
**Problem:** 
installing the module with this json: https://github.com/Pjb518/FoundryVTT-Level-Up-Official/releases/download/0.8.15/system.json

i get the following error: 
setup.js:292 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.dirname (node:path:654:5)
    at file:///<REDACTED_FOLDER>/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/installer.mjs:1:771

**Foundry version**: Version 10 - Build 291 (stable)
**Os Version:** Windows 10

**Comment by Pjb518** [comment]
May I ask why you were trying to install the system via a manifest link? The system has been registered with Foundry for well over a year now, so you can just search for Level Up in the package directory and install / update the system without any need for a manifest URL.

That aside, I just successfully installed the system using the link above, and this is also the manifest that Foundry uses to install and update the system via the package manager. We have well over a thousand downloads of the `0.8.15` system files, so this looks like a (likely temporary) problem with your Foundry installation than anything on our end.

**Comment by Melon-PieldeSapo** [comment]
because i cant find the module for some reason. 
![image](https://user-images.githubusercontent.com/3042317/225123458-af168259-b949-4d31-8be7-b61815656c08.png)
knowing that it has to be problem on my side ill try with a fresh foundry installation. 
Thanks

**Comment by Melon-PieldeSapo** [comment]
That makes sense.
