### ISSUE TITLE
BUG: NPC sheet not rendering changes to underlying Actor data

### ISSUE THREAD

**Issue by PhyDoesStuff** [Pjb518/FoundryVTT-Level-Up-Official#12]
Multiple issues observed when adding making modifications to an NPC Actor (both via the Foundry application and via web browser):

- NPC sheet does not update when first adding an Item (via "+Add X" buttons and via drag-and-drop from the Item Directory). In cases where the Item was added via an on-sheet button, changing the name of the Item will update the sheet. Closing and reopening the NPC sheet shows the new Item in both cases.
- NPC sheet does not update when deleting an Item from any section of the sheet (the Item appears to remain in the lists). Attempting to delete the Item again throws an error. Closing and reopening the sheet properly shows the Item as having been removed. Stack trace from the console:
Uncaught (in promise) Error: The key nCCZclGQbM2TZ3ZF does not exist in the EmbeddedCollection Collection
[Detected 1 package: system:a5e]
    get collection.mjs:106
    _preDeleteDocumentArray foundry.js:10294
    _deleteEmbeddedDocuments foundry.js:10267
    delete backend.mjs:214
    deleteDocuments document.mjs:410
    deleteEmbeddedDocuments document.mjs:558
    onDeleteItem ItemActionButtons.vue:52
    _sfc_render$E/_cache[3]< ItemActionButtons.vue:37
    withModifiers runtime-dom.esm-bundler.js:1466
    callWithErrorHandling runtime-core.esm-bundler.js:155
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:164
    invoker runtime-dom.esm-bundler.js:366
- Changes to Skill Proficiency, Special Senses, Damage Resistances, Damage Immunities, Damage Vulnerabilities, Condition Immunities, Languages do not render until sheet is closed and reopened.
- Changes to HP via the Sheet (modifying current HP) do not update HP bar graphic until sheet is closed and reopened.
- Changes to Max HP via the config dialogue requires closing and reopening sheet to render.
- Cannot change Current HP via the config dialogue.
- Edit Toggle does nothing until sheet is closed and reopened.

I'm seeing a lot of unregistered callbacks for hooks in the console, as well. Not sure if those are related, but hopefully it's helpful.

**Comment by PhyDoesStuff** [comment]
Additionally, filters appear to not be working, but their affects do apply when the sheet is closed and reopened.

**Comment by Pjb518** [comment]
Hey,

Thanks for letting me know about this. I can see the issue, but I have absolutely no idea how it occurred. It almost looks like an error caused by the automatic formatting.

I'll release a new version now with the two character fix 😄
