### ISSUE TITLE
[Bug] The action image dialog shows up behind the action dialog

### ISSUE THREAD

**Issue by Pjb518** [Pjb518/FoundryVTT-Level-Up-Official#126]
When setting an image for an action, the dialog pops up behind the one for the action. This is likely due to the fact that one is a TRL Svelte dialog, and the other is a basic Foundry one. Foundry's `bringToTop` method isn't able to account for the Svelte dialogs, which would have been an easy fix.

It does not appear that we can pass in an explicit `z-index` to the `FilePicker` either. We should look into whether there's a TRL version of the `FilerPicker`. If not, we need to figure out a way to fix this.

Overall, this is a minor inconvenience, but it makes the system look less polished.

**Comment by NekroDarkmoon** [comment]
Fixed
