### ISSUE TITLE
[Feat] Quantity Consumer

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#137]
Add a quantity consumer that can consume the number of items on an actor.

This needs to be able to show what kind of items are available on the actor and as such can only be completely configured when the item is on an actor.

**Comment by Pjb518** [comment]
I think we should make "ammunition" its own consumer and exclude ammunition items from the generic quantity consumer. This will allow us to provide some nice UX improvements for ammunition selection on sheets.
