### ISSUE TITLE
[Module Compatibility] Provide a configuration file to the Health Estimate module

### ISSUE THREAD

**Issue by Pjb518** [Pjb518/FoundryVTT-Level-Up-Official#139]
Health Estimate allows systems to provide a config file to load in system presets. This will allow A5e users to use Health Estimate without needing to do any setup.

https://github.com/mclemente/healthEstimate/tree/master/module/systems

We should provide a PR with a config file for A5e.

**Comment by neovista** [comment]
This is in progress and is close to being implemented.

**Comment by neovista** [comment]
Done. https://github.com/mclemente/healthEstimate/pull/229
