### ISSUE TITLE
[Chore] - Compendium - Resource (Manuever) Consumer

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#147]
Automatically add the `Resource Consumer` to all maneuvers that have an exertion cost of more than 0 and set the quantity to the correct exertion amount.

**Comment by Pjb518** [comment]
We should probably clean up the old exertion data as part of this issue, as well, and modify the maneuver summary section to make use of the resource consumption information, rather than the old exertion cost field.

**Comment by NekroDarkmoon** [comment]
Since this "pack migration" relies on `exertionCost` i'd like to leave it in there for a few updates so that if there's an issue we can revert and fix it.
