### ISSUE TITLE
[Refactor] Move to svelte for our system settings

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#216]
- [x] Re-do the system settings to use Svelte instead of handlebars.
- [x] Group settings into different tabs or sections.
- [x] Use our fancy svelte components to replace all the default components. 
- [x] Fix all localization of settings.
- [x] Properly hook up all settings to their default behavior.

**Comment by NekroDarkmoon** [comment]
For `0.11.0` only the conditions settings need to be updated.

**Comment by Pjb518** [comment]
Maybe we should make a separate issue for the conditions settings and reference it here. Right now, we're not going to be able to close this as part of the `0.11.0` milestone.

**Comment by NekroDarkmoon** [comment]
- [ ] #222

**Comment by Pjb518** [comment]
What's our progress on this @NekroDarkmoon?

**Comment by NekroDarkmoon** [comment]
Should be finished next update. Chat cards and effects have been moved. The rest need to be moved. The structure for it is already there, they just need to be moved.
