### ISSUE TITLE
[Refactor] Replace all 'none' values with null in the action config

### ISSUE THREAD

**Issue by Pjb518** [Pjb518/FoundryVTT-Level-Up-Official#231]
Several properties in the action config use 'none' instead of 'null' when the user does not wish to set an option. This is inconsistent across properties, and it's harder to work with programmatically, as we cannot rely on the falsiness of the value for various checks.

We should update the configuration components and migrate item data to use the new `null` value.

**Comment by NekroDarkmoon** [comment]
This should automatically be fixed when we move to data models for items.
