### ISSUE TITLE
[Feat] Clearer Prepared Spell/Equipped Item and maybe alternate states for spell preparation

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#235]
> At the moment, the current method for indicating that a spell is prepared or an item is equipped is very unnoticeable, just a symbol that goes from light grey to dark grey. Sure there's the filter but it would be nice to have something that makes it easier to tell at a quick glance. I like the method in the Tidy5eSheet module for the O5e system where an equipped item or prepared spell is highlighted green, it also allows them to utilize having other spell preparation mode such as always prepared and innate (which I was also gonna make a feature request for but thought I'd ask in this one instead). I've attached an image to show it, green is prepared, blue is always prepared, red is innate, they use purple for pact magic (although a5e pact magic is different now), yellow for at-will, and still use grey for not prepared.
> 
> ![image](https://github.com/Pjb518/FoundryVTT-Level-Up-Official/assets/49667684/7e18b8e3-b524-4e4c-bfcf-9f1173d12335)

From MangoBay [Discord]

**Comment by Pjb518** [comment]
Partially complete in 37c783cd66ea3182431a96b08870e404fbb411ed and 10bd02d4198db9eb7720514187cb1ebd0a6a1d90. Additional preparation and equipment modes still need to be added.
