### ISSUE TITLE
[Enhancement] Add stealth disadvantage as a toggle in the new AC configuration

### ISSUE THREAD

**Issue by Pjb518** [Pjb518/FoundryVTT-Level-Up-Official#247]
We should provide a checkbox to indicate whether wearing a given piece of armour penalises the wearer with disadvantage on stealth checks. I think this would be fine as part of the general AC config we provide for all items.

We can also potentially provide some automation for this by pre-selecting disadvantage in the roll dialog. Alternatively, we can provide a note about disadvantage if the character has disadvantage on stealth checks due to armour.

**Comment by NekroDarkmoon** [comment]
Depends on #255.
