### ISSUE TITLE
Feat: Add Broken Condition to Item

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#27]
Add the broken condition to item data.

This includes the following: 
- [x] Add configuration in the item template to signify the broken condition.
- [x] Add a user interface in the properties tab to change this information.
- [ ] Add a small indicator to Item Wrapper for the actor sheet to easily apply the condition.

**Comment by JoshLaunchcode** [comment]
This one seems a bit more in-depth compared to my previous PR's and gets into some aspects of the system I haven't explored yet. I'd be down to give it a go!

**Comment by Pjb518** [comment]
This was merged in as part of #35. Closing this issue.
