### ISSUE TITLE
[Bug] The new crit damage toggle incorrectly indicates a crit when one of the formulae has an unresolved MathTerm

### ISSUE THREAD

**Issue by Pjb518** [Pjb518/FoundryVTT-Level-Up-Official#274]
I was having an issue where a roll was always showing up as a crit, and this was preventing the crit toggle from functioning properly.

The formula for the current damage roll was `1d8 + 3[Mod] + 2[Sniper] + 2d6[Sneak Attack]`, but the roll stored in `baseRoll` was `1d8 + 3[Mod] + 2[Sniper] + ceil(3 / 2)d6[Sneak Attack]`. We use a comparison between the current roll and `baseRoll` to determined if a given roll is a crit, so this comparison is not working as intended in this case.

I'm currently unsure why the `baseRoll` is showing up differently, as the `roll` is assigned a copy of `baseRoll`:
```js
const baseRoll = await new Roll(rollFormula).evaluate({ async: true });
let roll = baseRoll;
```
These should be identical. Requires further investigation.

**Comment by NekroDarkmoon** [comment]
Hmm,  pretty sure it's the evaluate that causes the formula to be simplified no? 🤔

**Comment by Pjb518** [comment]
> Hmm, pretty sure it's the evaluate that causes the formula to be simplified no? 🤔

The `evaluate` definitely simplifies the formula, but the roll is evaluated before being assigned to `baseRoll` (the unsimplified one), and then `roll` is just assigned the exact same value as was assigned to `baseRoll`. So, how is `roll` more simplified than `baseRoll` when they're the same object? 🤷‍♂️

**Comment by Pjb518** [comment]
The new dice cleanup branch doesn't have this issue, it seems. I'm going to merge that code into dev and call it a day, I think.
