### ISSUE TITLE
Condition Icon Counters

### ISSUE THREAD

**Issue by kunaiknife452** [Pjb518/FoundryVTT-Level-Up-Official#275]
While the recent update to Status Effects was excellent, it *seems* to break compatibility with the module "Status Icon Counters".

While this isn't the end of the world, it could be a useful feature to integrate or support in the future, especially with stackable conditions like Strife and Fatigue. This could potentially even allow for a direct link between the status effect and the counter in the character sheet.

Example image from the module mentioned:
![sample](https://github.com/Pjb518/FoundryVTT-Level-Up-Official/assets/59149627/9ead10d6-f8ba-425e-b453-34a49cd37799)

**Comment by NekroDarkmoon** [comment]
This will be coming in the next few updates. The refactor of the conditions interface and the change in how it works was done to make it easier to support this feature along with some other improvements.

**Comment by NekroDarkmoon** [comment]
Will be part of the next release.
