### ISSUE TITLE
Feat: Add a Spell Modifier Shortcut

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#28]
Provide a "spell modifier" shortcut in `rollData` for users to reference. This can be in the form of `@spellMod`.

*References:*
RollData can be made available in the `actor.getRollData()` method.
https://github.com/Pjb518/FoundryVTT-Level-Up-Official/blob/627c07c22ac5cbf3e2c4ec2e344e7be0b319f6f1/src/modules/actor/entity.js#L243-L267

An example of how to get the spellcasting ability modifier can be found here.
https://github.com/Pjb518/FoundryVTT-Level-Up-Official/blob/627c07c22ac5cbf3e2c4ec2e344e7be0b319f6f1/src/modules/utils/calculateSpellDC.js#L3-L13

**Comment by JoshLaunchcode** [comment]
I'll take this one on!
