### ISSUE TITLE
[Feat] Add a setting to use 5e-style death roll rules for natural 1s and 20s.

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#287]

**Comment by Pjb518** [comment]
This is already part of the system: 
<img width="584" alt="image" src="https://github.com/Pjb518/FoundryVTT-Level-Up-Official/assets/33249712/3954401b-f15f-4154-b51a-cbee71c2ed27">
