### ISSUE TITLE
[Request] Ability to Rearrange / Reorganise Inventory

### ISSUE THREAD

**Issue by Rogue1174** [Pjb518/FoundryVTT-Level-Up-Official#3]
At the moment Inventory can get quite messy when a lot of items are added, so it'd be great to have either sections such as weapons, equipment, and consumables (similar to Foundry's built in 5e system) or the ability to move inventory within the sheet so that it may be organized as desired.

**Comment by Pjb518** [comment]
Hey,

The ability to sort items (manually and automatically) is coming soon. The system won't be grouping items by type like in 5e, however, as we're going to rely on a much richer set of filters instead.

At the moment, the system doesn't really have a concept of what a weapon is, or whether something is armour, but once that has been included, filters will come along with it 🙂

**Comment by Rogue1174** [comment]
> Hey,
> 
> The ability to sort items (manually and automatically) is coming soon. The system won't be grouping items by type like in 5e, however, as we're going to rely on a much richer set of filters instead.
> 
> At the moment, the system doesn't really have a concept of what a weapon is, or whether something is armour, but once that has been included, filters will come along with it 🙂

That's great to hear! Excited to see it :)

**Comment by Pjb518** [comment]
@Rogue1174 Just for future reference, issues on here should stay open until they're resolved. The issue tracker can serve as a sort of to-do list 🙂

**Comment by Rogue1174** [comment]
> 

Fantastic! Thanks :) I'll also keep the resolving issues in mind in future.
