### ISSUE TITLE
Feat: Jack of all Trades implementation

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#34]
Implement jack of all trades for actors. 

This task includes the following: 
- [ ] Create a setting to enable jack of all trades in actor settings. Alternatively, this can be applied via active effects but the former approach is preferred over the latter.
- [ ] Update prepare skills to account for jack of all trades by checking the settings flag.
- [ ] Update the skill page on the actor sheet to provide an indication of half proficiency.

https://github.com/Pjb518/FoundryVTT-Level-Up-Official/blob/a1d2eb99fd01c7704d17e4599ac7f5660b8b492b/src/documents/actor.js#L216-L218

**Comment by JoshLaunchcode** [comment]
I would love to work on this one and get a feel for the skills side of things.

**Comment by Pjb518** [comment]
Merged into `development` as part of #37.
