### ISSUE TITLE
Change A5EDataModel extension from `foundry.abstract.DataModel` to `foundry.abstract.TypeDataModel`

### ISSUE THREAD

**Issue by JPMeehan** [Pjb518/FoundryVTT-Level-Up-Official#359]
The [official documentation](https://foundryvtt.com/article/system-data-models/) hasn't been updated since v11 (There's a long-running [thread on the core software discord](https://discord.com/channels/170995199584108546/1150115023713210429) bugging them to fix this, but it's been several months and it's still not corrected).

This shouldn't be a breaking change - the [TypeDataModel](https://foundryvtt.com/api/classes/foundry.abstract.TypeDataModel.html) class just adds some empty functions for `prepareBaseData` and `prepareDerivedData` - but will be necessary in v12 to prevent [some breakages](https://github.com/foundryvtt/foundryvtt/issues/10411).

**Comment by NekroDarkmoon** [comment]
Yup been keeping an eye on it. We haven't done anything for v12 yet per day but we'll be addressing those as soon as our current release series is completed.

**Comment by JPMeehan** [comment]
TypeDataModel is available in v11, it's just optional.
