### ISSUE TITLE
Chore: Update on:click events

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#39]
The new svelte version introduces a new handler for `on:press`, we should replace all uses of `on:click` with `on:press` events. This helps us get rid of all the `<!-- svelte-ignore a11y-click-events-have-key-events -->` comments and increases accessibility.

**Comment by Pjb518** [comment]
Closing this for now, as it breaks a lot of stuff, and I'm not yet sure of the reason.
