### ISSUE TITLE
Actor sheet does not support dropping journal pages

### ISSUE THREAD

**Issue by paulyhedral** [Pjb518/FoundryVTT-Level-Up-Official#395]
I am working on a Foundry module that supports creating parcels of items that can be given to a PC by dropping the parcel onto the actor sheet. The parcel is implemented using JournalEntry and JournalEntryPage, and relies on the `dropActorSheetData` hook to fire in order to copy the items to the PC. However, this system only seems to support dropping `Item`s on the actor.

Can you add support for additional types to be dropped on the actor?

**Comment by NekroDarkmoon** [comment]
I can add the hook for this back in but could you elaborate on how exactly the journal converts to items? We have special handling for different types of items. Depending on how you go about this the added items might not go through the proper drop procedures.

**Comment by paulyhedral** [comment]
@NekroDarkmoon In answer to your question: the journal contains item links that are copied to the actor. Basically like this: 
```
const item = await fromUuid(linkInfo.id);
await Item.create([item], { parent: actor });
```
