### ISSUE TITLE
Request - integrate with Argon Combat Hud

### ISSUE THREAD

**Issue by flynnkd** [Pjb518/FoundryVTT-Level-Up-Official#4]
I realise this is early on, and it requires the other side to get involved, but ACH is really good.  Ta :)

**Comment by NekroDarkmoon** [comment]
The author of the module specifically said they will not be supporting any other systems.

**Comment by Pjb518** [comment]
Yeah, unfortunately this isn't going to be possible. Please see [the FAQ section](https://github.com/theripper93/enhancedcombathud#faqs) of the Argon repo.

> Q: Can you add compatibility for X system? A: No, Argon is hardcoded for dnd5e. If you want you can make a fork for a specific system. You have to include the licence section and credit the original authors (theripper93, Mouse0270) and include links to our patreon page\website (if provided).

That's not to say that somebody won't make a fork or a similar solution for A5e, but it looks like the existing Argon module won't ever be compatible with Level Up.

**Comment by rapus95** [comment]
As I just stumbled over this, the module was rewritten and now consists of a core-module which is system agnostic and a system specific module. This allows for any other system to extend the combat hud. So this issue could be reopened.
https://wiki.theripper93.com/free/enhancedcombathud#for-developers

**Comment by NekroDarkmoon** [comment]
> As I just stumbled over this, the module was rewritten and now consists of a core-module which is system agnostic and a system specific module. This allows for any other system to extend the combat hud. So this issue could be reopened. https://wiki.theripper93.com/free/enhancedcombathud#for-developers

We still won't be adding support for this as we already have a lot of work to do with the system and we will also be including our own HUD built into the system. That said if somebody wants to make a module for the system that adds compatibility they are more than welcome to do so 😄
