### ISSUE TITLE
0.9.0 Master Issue

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#41]
Tasks and issues that need to be completed to publish `0.9.0`. 

**Generic Issues:**
- [x] #42 

**Actor Sheet Issues:**
- [x] #54 
- [x] #56 
- [x] #57 
- [x] #58 

**Item Sheet Issues:**
- [x] #45 
- [ ] #46 
- [x] #31 
- [ ] #48 
- [x] #49 
- [x] #50
- [x] #53 
- [ ] #55 
- [x] #56 
- [x] #61 

**Chat Card Issues:**
- [ ] #52 

**New Item Types:**

**Migrations:**
- [x] #51

**Comment by Pjb518** [comment]
I think this issue may have outlived its usefulness. We can already filter issues by their milestone, and this issue isn't being updated with new tasks. We have 11 open issues for `0.9.0`, but there are only 3 listed here, and to keep updating this issue adds another maintenance burden.

Closing this for now, but feel free to reopen it if you think there's good reason to.
