### ISSUE TITLE
[Request(s)] - Dark Mode and Roadmap

### ISSUE THREAD

**Issue by AceAckbar** [Pjb518/FoundryVTT-Level-Up-Official#5]
Loving the work so far, and I know it's super early days, but I was hoping for two things.

1. Dark Mode version of the character sheets. 
And:
2. Some sort of roadmap. This doesn't need to be completely accurate, or explain what is being worked on next (as nice as that would be), but just a list of all features planned. 

Thanks for your hard work, and looking forward to whatever comes of this.

**Comment by Pjb518** [comment]
Hey,

Dark Mode (as well as other themes) are a planned feature, but that sort of thing is fairly low priority. The goal right now is to add in as much as we can to best support the system mechanics, and to make the game smoother to run on Foundry.

As for a roadmap, there's one pinned in the `online-tools` channel of the [EN World Discord server](https://discord.gg/7YVguZHg), but I can post you some notes here. These are the high-priority features which are still outstanding, but it's not an exhaustive list of everything to come:

- Damage scaling based on spell level and resource consumption.
- An Active Effects interface.
- The ability to configure the roll process when activating an item.
- Item subtypes with specialised configuration for each (partially completed)
- More detailed filtering options and automatic sorting options (partially completed)
- Further automated resource consumption
- Improvements to the system forms
- A suite of hooks to aid in system extensibility through modules
- A collection of system compendia containing A5e monsters, items, features, and spells.
- A built in action HUD for both players and Narrators.

**Comment by AceAckbar** [comment]
This is fantastic. Joined the Discord to keep up with it. I'm excited, thank you so much! :D

**Comment by Pjb518** [comment]
Closing this issue in favour of a more specific sheet colour configuration issue: #138.
