### ISSUE TITLE
[Feat] Configure items on Actor Sheet

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#56]
Add configuration to actor sheet to allow for creation, deletion, and editing of items.

Related issues: 
- #55 
- #46

**Comment by Pjb518** [comment]
Items can now be deleted and edited from the actor sheet. Buttons to add new items still need to be implemented.

**Comment by NekroDarkmoon** [comment]
Items can now be added as well.
