### ISSUE TITLE
[Feat] Add a delete confirmation dialog

### ISSUE THREAD

**Issue by Pjb518** [Pjb518/FoundryVTT-Level-Up-Official#58]
When clicking the delete button for items on an actor sheet, we should provide an optional dialog to confirm the deletion. This will help prevent accidental deletions.

**Comment by shyamtawli** [comment]
@Pjb518 Where can I see the issue ? 
Can you provide the hosting link.

**Comment by Pjb518** [comment]
> @Pjb518 Where can I see the issue ? Can you provide the hosting link.

I'm sorry, but I have no idea what you're asking for. Could you elaborate on what you mean?

You may also want to check out the [collaborators guide](https://github.com/Pjb518/FoundryVTT-Level-Up-Official/wiki/Contributing-Guide) if you're interested in helping out with this particular feature.

**Comment by Pjb518** [comment]
1612ce40da9e5bd945363577d0ba61174d275d88 adds a confirmation dialog for deleting items and an associated setting to disable the dialog. Closing this issue as completed.
