### ISSUE TITLE
Requests - Several resources

### ISSUE THREAD

**Issue by djorjow** [Pjb518/FoundryVTT-Level-Up-Official#6]
An overview tab of your character sheet like the module tidy5esheet does would be need!

That would also give us the resources part where we can track things such as sorcery points or other stuff.

Another feature I'd like to see is an "always prepared" version of preparing spells for classes that just learn the spells and are not prepared casters.

**Comment by djorjow** [comment]
As well as a quantity tracker for your items :D

**Comment by Pjb518** [comment]
> As well as a quantity tracker for your items :D

This, along with further automatic resource consumption is planned for the next release 🙂

The resources part can certainly be added, but I have slightly different plans regarding preparation modes. Level Up will soon allow you to have several spell books, and there will be various settings for preparation included as part of that.

**Comment by Pjb518** [comment]
Resources are included in the upcoming `1.0.0` release. Automatic resource consumption is also included in that release, so I think this can be closed.
