### ISSUE TITLE
[Feat] Add a heritage item type

### ISSUE THREAD

**Issue by Pjb518** [Pjb518/FoundryVTT-Level-Up-Official#69]
We need to add a heritage item type, similar to those for backgrounds, cultures, and destinies that are also coming in `0.9.0`. A heritage type needs to hold various pieces of information, such as:

- Size category
- Creature types
- Movement modes and speeds
- Special senses
- Traits and features
- Fluff and lore

Dragging a heritage item onto an actor sheet will open a new dialog window where users can choose between features and so on.

There is currently working being carried out towards this in PR #36, but work seems to have stalled for the time being.

**Comment by NekroDarkmoon** [comment]
Still need to add a details page for size and creature types I guess. I don't think it makes much sense to make separate features for these with permanent effects.
