### ISSUE TITLE
[Feat] Add a setting to reverse the alt behaviour for initiative rolls

### ISSUE THREAD

**Issue by Pjb518** [Pjb518/FoundryVTT-Level-Up-Official#83]
Currently, any time a user wants to skip the initiative roll dialog, they need to hold `alt` while pressing the roll button. We should provide a setting to change this behaviour so that the initiative roll dialog only shows when `alt` is pressed. This will provide a better experience for people running 5e or people who just don't really use the initiative rules for NPCs.

This should be a client setting. Different players may prefer a different option here, and GMs may want a different option to their players.

**Comment by JoshLaunchcode** [comment]
I'll grab this one

**Comment by Pjb518** [comment]
Added as part of fixes in caf824380058d101cef71a8a43d54b7c39f0280e. Closing this as completed.
