### ISSUE TITLE
[Refactor] Standardise tags across the system

### ISSUE THREAD

**Issue by Pjb518** [Pjb518/FoundryVTT-Level-Up-Official#85]
During the many months of development to get to `0.9.0`, new components have been created that haven't been ported back to the earlier work. One example of this is the various checkbox and radio group tags. In addition to adding unnecessary duplicate code, these tags are using old system colours, and so they don't match the new aesthetic.

We should do a once over of all dialog components and item property components to locate any sections that can be refactored to use the newer `CheckboxGroup` and `RadioGroup` implementations.

**Comment by NekroDarkmoon** [comment]
Completed.
