### ISSUE TITLE
Chat card background css overwrites whisper distinction

### ISSUE THREAD

**Issue by Aushou** [Pjb518/FoundryVTT-Level-Up-Official#9]
A line in the chat-card style sheet overwrites the backgrounds for all chat cards. While a minor change, and better for legibility, it's currently overwriting Foundry's default ability to visually distinguish between types of chat messages. In my game's use particular use case, it is impossible to tell when an incoming message is a single-target whisper. (A multi-target whisper includes a To: line indicating all recipients). There may be other scenarios this affects; for instance, different role types are also visually distinguished by the chat-card's background color.
 
Would you consider removing this change, or implementing other classes to maintain a visible difference between chat types?

### Link To Relevant Code
https://github.com/Pjb518/FoundryVTT-Level-Up-Official/blob/63927255c800b6a3ca4301bac51158b6ffabbac0/src/scss/layout/_chat-card.scss#L4

### Screenshots
**Expected:** Captured by using the development tools to nullify the `background` attribute in the `#chat-log .message` class. The lower card is a whisper, the top is not.
![Cropped screenshot of two chat cards, where the lower chat card is significantly lighter in color](https://user-images.githubusercontent.com/7462497/152831279-e564b975-bcf4-4893-98cc-9c76c5975c14.png)

**Current:** Same cards, no modifications. The lower card is a whisper, the top is not. 
![Cropped screenshot of two chat cards, where the backgrounds are identical in color](https://user-images.githubusercontent.com/7462497/152831997-c60f8f12-f3bb-496c-9039-d919889c8888.png)

**Comment by Pjb518** [comment]
Hey,

Thanks for the report. This issue is already on my radar, and I have fixes planned for the upcoming release 🙂

I won't be reverting the colour change, because this is to maintain colour consistency with the sheets, but I can provide additional styles to provide different colours for different message types. I'm also planning to add some sort of icon or other indicator for the different message types, as I don't think colours alone are sufficient.

I'll leave a message here when the relevant release goes out.

**Comment by Aushou** [comment]
Sounds great! I'd definitely be happy to see icons or further differentiation, I agree relying on background colors isn't really an ideal solution.

**Comment by Pjb518** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Restore chat card background colours for different roll modes and add a roll mod icon](https://trello.com/c/aR8D4tlx/12-restore-chat-card-background-colours-for-different-roll-modes-and-add-a-roll-mod-icon)

**Comment by Pjb518** [comment]
Closing as this has been fixed in the upcoming `0.7.0` 🙂
